redis_url = "redis://localhost:6379/0"
extra_modules = ["sotopia.experimental.nodes.openhands_node"]


[[nodes]]
node_name = "runtime"
node_class = "openhands"

[nodes.node_args]
output_channels = ['Runtime:Agent']
input_channels = ['Agent:Runtime']