redis_url = "redis://localhost:6379/0"
extra_modules = ["examples.experimental.group_discussion_agents.group_discussion_agents"]

[[nodes]]
node_name = "Jack"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 15
output_channel = "Jack"
input_text_channels = ["Jane", "John"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a total of 3 stone pickaxes. 
The complete process for crafting a "stone_pickaxe" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 2 pieces.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 4 planks to craft a "crafting_table"!!!
4. Use 2 planks to create 4 "stick"!!!!
5. Use 3 planks and 2 sticks to craft a "wooden_pickaxe"!!!
6. Use the wooden pickaxe to mine "stone", collecting at least 3 pieces. Before obtaining stone, make sure to type !inventory to check if you have a "wooden_pickaxe". If you don’t, type !craftable to check if you can craft a "wooden_pickaxe".
7. Open the "crafting_table" and use 3 pieces of stone and 2 sticks to craft a "stone_pickaxe"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "Jack"

[[nodes]]
node_name = "Jane"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 19
output_channel = "Jane"
input_text_channels = ["Jack", "John"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a total of 3 stone pickaxes. 
The complete process for crafting a "stone_pickaxe" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 2 pieces.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 4 planks to craft a "crafting_table"!!!
4. Use 2 planks to create 4 "stick"!!!!
5. Use 3 planks and 2 sticks to craft a "wooden_pickaxe"!!!
6. Use the wooden pickaxe to mine "stone", collecting at least 3 pieces. Before obtaining stone, make sure to type !inventory to check if you have a "wooden_pickaxe". If you don’t, type !craftable to check if you can craft a "wooden_pickaxe".
7. Open the "crafting_table" and use 3 pieces of stone and 2 sticks to craft a "stone_pickaxe"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "Jane"

[[nodes]]
node_name = "John"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 23
output_channel = "John"
input_text_channels = ["Jack", "Jane"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a total of 3 stone pickaxes. 
The complete process for crafting a "stone_pickaxe" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 2 pieces.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 4 planks to craft a "crafting_table"!!!
4. Use 2 planks to create 4 "stick"!!!!
5. Use 3 planks and 2 sticks to craft a "wooden_pickaxe"!!!
6. Use the wooden pickaxe to mine "stone", collecting at least 3 pieces. Before obtaining stone, make sure to type !inventory to check if you have a "wooden_pickaxe". If you don’t, type !craftable to check if you can craft a "wooden_pickaxe".
7. Open the "crafting_table" and use 3 pieces of stone and 2 sticks to craft a "stone_pickaxe"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "John"

[[nodes]]
node_name = "record"
node_class = "record"

[nodes.node_args]
jsonl_file_path = "log.jsonl"

[nodes.node_args.record_channel_types]
"Jack" = "agent_action"
"Jane" = "agent_action"
"John" = "agent_action"

[[nodes]]
node_name = "tick"
node_class = "tick"