redis_url = "redis://localhost:6379/0"
extra_modules = ["examples.experimental.group_discussion_agents.group_discussion_agents"]

[[nodes]]
node_name = "Jack"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 15
output_channel = "Jack"
input_text_channels = ["Jane", "John"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a "stone_pickaxe". YOUR TASK IS TO CRAFT A "crafting_table".
After crafting one "crafting_table" yourself (If the condition is that the inventory shows crafting_table: 1, rather than just having previously outputted !craftRecipe(\"crafting_table\", 1)), use the command !goToPlayer(\"John\", 0) to go to John's location.
Then, use the command !placeHere(\"crafting_table\") to give John the "crafting_table". Afterward, please use the command !moveAway(5) once to maintain distance.

The complete process for crafting a "crafting_table" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 1 piece.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 4 planks to craft a "crafting_table"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "Jack"

[[nodes]]
node_name = "Jane"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 19
output_channel = "Jane"
input_text_channels = ["Jack", "John"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a "stone_pickaxe". YOUR TASK IS TO CRAFT 4 "stick".
After crafting 4 "stick" yourself (If the condition is that the inventory shows stick: 4, rather than just having previously outputted !craftRecipe("stick", 4)), use the command !goToPlayer("John", 0) to go to John's location.
Then, use the command `!givePlayer(\"John\", \"stick\", 4)` to give John 4 "stick" (number like 4 does not need to use double quotation marks). Afterward, please use the command !moveAway(5) once to maintain distance.

The complete process for crafting 4 "stick" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 1 piece.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 2 planks to create 4 "stick"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "Jane"

[[nodes]]
node_name = "John"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 23
output_channel = "John"
input_text_channels = ["Jack", "Jane"]
input_tick_channel = "tick/secs/1"
goal = """
You and your friends need to craft a "stone_pickaxe". Jack will help you craft a "crafting_table" and give it to you, while Jane will craft 4 "stick" and give them to you.
Before this, you should collect some logs and process them into at least 3 planks. Once you have received the "crafting_table" and 4 "stick", you can proceed to craft the "stone_pickaxe" as follows.

The complete process for crafting a "stone_pickaxe" in Minecraft is as follows (Please craft or obtain the items strictly in the following order):
1. Collect logs, such as "oak_log", "spruce_log" or "birch_log" with at least 2 pieces.
2. Convert logs into planks ("birch_planks", "spruce_planks" or "oak_planks"). Each log can produce 4 planks.
3. Use 4 planks to craft a "crafting_table".
4. Use 2 planks to create 4 "stick".
5. Use 3 planks and 2 sticks to craft a "wooden_pickaxe".
6. Use the wooden pickaxe to mine "stone", collecting at least 3 pieces. Before obtaining stone, make sure to type !inventory to check if you have a "wooden_pickaxe". If you donâ€™t, type !craftable to check if you can craft a "wooden_pickaxe".
7. Open the "crafting_table" and use 3 pieces of stone and 2 sticks to craft a "stone_pickaxe"."""
model_name = "gpt-4o-2024-11-20"
agent_name = "John"

[[nodes]]
node_name = "record"
node_class = "record"

[nodes.node_args]
jsonl_file_path = "log.jsonl"

[nodes.node_args.record_channel_types]
"Jack" = "agent_action"
"Jane" = "agent_action"
"John" = "agent_action"

[[nodes]]
node_name = "tick"
node_class = "tick"