redis_url = "redis://localhost:6379/0"
extra_modules = [
    "examples.experimental.sotopia_original_replica.llm_agent_sotopia",
    "examples.experimental.nodes.chat_print_node",
    "sotopia.experimental.agents.moderator",
    "sotopia.experimental.agents.evaluators"
]


[[nodes]]
node_name = "moderator"
node_class = "moderator"
[nodes.node_args]
output_channels = [
    "moderator:Jack",
    "moderator:Jane"
]
input_channels = [
    "Jack:moderator",
    "Jane:moderator"
]
evaluator_channels = [["evaluator:moderator","moderator:evaluator"]]
agent_mapping = { "moderator:Jack" = "Jack","moderator:Jane" = "Jane"}
scenario = "Two friends are sitting in a cafe and catching up with each other's lives."
max_turns = 3
push_to_db = false
evaluate_episode = false
use_pk_value = false


[[nodes]]
node_name = "Jack"
node_class = "llm_agent"

[nodes.node_args]
input_channels = ["moderator:Jack"]
output_channel = "Jack:moderator"
goal = "Your goal is to borrow 5000 dollars from Jane."
model_name = "gpt-3.5-turbo"

agent_name = "Jack"
[nodes.node_args.background]
occupation = "construction worker"



[[nodes]]
node_name = "Jane"
node_class = "llm_agent"

[nodes.node_args]
input_channels = ["moderator:Jane"]
output_channel = "Jane:moderator"
goal = "Your goal is to help Jack however, you are in a finicial crisis yourself and can only afford to give him 500 dollars."
model_name = "gpt-4"

agent_name = "Jane"
[nodes.node_args.background]
occupation = "gardener"



[[nodes]]
node_name = "chat_print"
node_class = "chat_print"

[nodes.node_args.print_channel_types]
"Jack:moderator" = "agent_action"
"Jane:moderator" = "agent_action"

[nodes.node_args]
env_agents = [
    "Jack",
    "Jane"
]

[[nodes]]
node_name = "evaluator"
node_class = "evaluator"

[nodes.node_args]
input_channels = ["moderator:evaluator"]
output_channels = ["evaluator:moderator"]
model_name = "gpt-4"


[[nodes]]
node_name = "redis_agent"
node_class = "redis_agent"

[nodes.node_args]
input_channels = ["moderator:redis_agent"]
output_channels = ["redis_agent:moderator"]
control_channel = ["redis_agent:websocket_uuid"]
